### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by ghost** [t3rmin8tor/kodi-player-core-factory-install#11]
![screenshot 2017-07-22 13 53 25](https://user-images.githubusercontent.com/30375754/28493548-bf0c7058-6ee6-11e7-8667-b7842516efd7.png)

also, vlc and mpv do not run when i select them in kodi. im guessing the paths are wrong. im on windows 8.1.  Saving video url closes the stream, doesn't seem to save anything.

**Comment by t3rmin8tor** [comment]
could you please state which version of rip record you are using as i can not assist without this information

**Comment by ghost** [comment]
i used the 2.2 installer

**Comment by t3rmin8tor** [comment]
hi lsl17  there is a known issue with v 2.2 and windows 7  8  and 8.1 not creating the /tmp folder ...... basically the mentioned windows versions have a crazy UAC policy which denies permission on some programs within Program Files and Program Files (x86)

i apreciate that this is inconvenient  however a solution is being worked on 

for the time being i would suggest using v2.0 this version does not appear to have such issues 
i will keep you updated on the progress of the fix for v2.2 

i hope this helps  if yo need further assistance dont hesitate to ask

**Comment by ghost** [comment]
i still got that temp issue with v2.0, but its saving the recording to my desktop so i guess it doesnt matter. and i am seeing progress in the cmd window, one question. how do i stop the recording once its started? like if i only want to record a certain amount?

**Comment by t3rmin8tor** [comment]
the commad to run rip record from cmd line is 

bash rip-record  video-file-name.txt   -t 00:00:00     
so to record for  10 minutes will be 

bash rip-record video-file-name.txt -t 00:10:00
1 hr would be  -t 01:00:00 

the best way to remember is    -t HH:MM:SS 

hope this helps

**Comment by steve55792** [comment]
HI, Is117: Did you finally get the issues fixed  with the program?

**Comment by ghost** [comment]
Yeah lol I'm good, it's working well on v2.0

**Comment by ghost** [comment]
Thanks for the help

**Comment by steve55792** [comment]
What was the issues you had because i tried all 3  downloads and it still didnt work for me. The issues I had was  i got an error say line 97 ffmpeg  command not found. and when i have a movie playing and i open the menu in kodi  with Y to use the mpv player all it did is went to the begging of kodi. I think ill try 2.0 again.
