### ISSUE TITLE
Can't get GUI's to work 

### ISSUE THREAD

**Issue by peanut9779** [t3rmin8tor/kodi-player-core-factory-install#13]
I've tried getting the all windows version GUI's to work to no avail...upon playing a movie and hitting the y key to bring up the drop down menu I've tried just about every option. I usually get a cmd window that flashing open and closed it an instant and if I hit the record button the cmd window opens and the get these errors in the screen shot. I have not tries doing a manual install of everything yet...that maybe my next attempt. 
![playercorefacturyerror](https://user-images.githubusercontent.com/25312843/30790313-dbb7c934-a170-11e7-8026-d45654c83d9b.jpg)
 
I appreciate any help you can give on this....thanks! 

Also included is my kodi log file that has a bunch of player not found under the playercorefactory dir.

[kodi.log](https://github.com/t3rmin8tor/kodi-player-core-factory-install/files/1328162/kodi.log)

This is with version 2.2 running with updated patch. Also now I can't even view videos with Kodi. As soon as I hit the play button it just opens a blank cmd prompt and dumps a url on the desktop. Nothing else happens with the other menu options.

![v2 2 w-patch error](https://user-images.githubusercontent.com/25312843/30793219-fe10057c-a185-11e7-9297-babb93e10b59.jpg)

**Comment by NapoleonWils0n** [comment]
hi mate

i think the latest windows update is causing a few permiwsion issues with the installer

there is a new and improved python version of the script coming very soon
the windows installer is just being finished off

id hold off trying to do a manual install of the bash version as its a bit of a pain

hopefully the windows installer for the python version will be ready in the next few days

**Comment by peanut9779** [comment]
Sweet! Thanks for the reply!!

**Comment by peanut9779** [comment]
oh just a reminder...you might want to check the patches. The versions are mixed up between 32 and 64 bit on v2.2 and v2.0 both versions use the same path (program files, should be program files (x86) for 64 bit) I think and all versions say it's 1.8 inside the script.

**Comment by NapoleonWils0n** [comment]
hi mate

thanks for the feedback

the installer for the new python version should be ready soon
i think it just needs a few tweaks

**Comment by peanut9779** [comment]
cool I can't wait...thanks for all the help!

**Comment by NapoleonWils0n** [comment]
hi peanut 

no problem mate
just wanted to give you a heads up that the new version will be ready soon

the new version of the script is written in python 3

Ive come up with a new way to convert urls from Kodi into ffmpeg and mpv commands with python
to record from within Kodi or on the command line and use mpv as an external player

the new python script is called pilfer and works on windows, mac, linux and freebsd

[pilfer](https://github.com/NapoleonWils0n/pilfer)

if you are on a mac, linux and freebsd you have to install the programs and scripts manually

it takes about 3 or 4 minutes to install everything on linux or freebsd 
and on a mac it takes 20 to 30 minutes because you have to install xcode tools and homebrew

the script can be installed on mac linux or freebsd now
the windows installer just needs a couple of tweaks

so im going to do the offical launch as it were when the windows installer is ready
ill do a new video as soon as the windows installer is ready

the windows version has an installer to install all the programs and scripts 
and also has gui desktop program which will let you schedule recordings as well

**Comment by steve55792** [comment]
Hi NapoleonWilson, I was wondering if the windows version of this pilfer is done cause i see there is a written instructions step by step to install it for windows. Is this going to work with tr3min8tor's  windows version of rip-record.
                                                                                                   Thanks
                                                                                                      Steve

**Comment by NapoleonWils0n** [comment]
hi mate

still finishing a few things off so not ready yet

i think you will need to uninstall rip-record before installing pilfer

**Comment by t3rmin8tor** [comment]
will definately have to uninstall rip-record  as with the new pilfer  installation rip-record becomes obsolete

**Comment by t3rmin8tor** [comment]
new release is out be sure to uninstall rip-record before  installing pilfer 
https://github.com/t3rmin8tor/pilfer-installer/blob/master/README.md

**Comment by steve55792** [comment]
Hi Tr3mn8tor, much changed with the program? Ive been away for 4 days, just wondering if all been fixed with pilfer/rip-record, cause i just installed  everything and tried in Kodi and nothing. I tried record in kodi and saving it in a url, nothing. Is there something missing .

**Comment by NapoleonWils0n** [comment]
Hi Steve

The pilfer installer isnt quite ready yet
just working out a few issues with python path on 32 and 64bit versions of windows

But the manual install is tested and working and will take about 15 minutes to set up, 
if you want to gice it a go  [pilfer windows manual install](https://github.com/NapoleonWils0n/pilfer#windows-set-up)
