### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/kodi-player-core-factory-install#6]
Hi, i downloaded new version rip-record 1.8  but it wont install the new version  With this new version will it help with recording inside kodi? I can not save an url  inside kodi.

**Comment by NapoleonWils0n** [comment]
hi mate, i just installed 1.8 and am having the same issue
the problem seems to be the installer isnt adding anything to the windows system path

i dont know what the installer adds to the windows system path so you could manually add it

would be good if there was some documentation about what the installer adds to the windows system path
just in case the installer doesnt add it, then the user could manually add it to the system path

**Comment by steve55792** [comment]
even with the git repo I cant save an url on the desktop inside of kodi. His rip-record program work  okay.
inside the command prompt that is

**Comment by steve55792** [comment]
I sswitched builds in kodi and now I can save urls.

**Comment by t3rmin8tor** [comment]
rip-record now updated to v 2.0
